### ISSUE TITLE
可笑之极!

### ISSUE THREAD

**Issue by chaseqaq** [sulianapp-com/sulianapp#5]
这不是芸众商城吗？转手就开源收费了？

**Comment by rainyang** [comment]
就你知道是吧，还可笑之极，芸众不收费么？我又不是盗版，我是官方代理，不知道就别在这里胡说

**Comment by newtiny** [comment]
那我就呵呵了 为什么我联系芸众销售别人说没有你这样的代理呢？别关闭啊？

**Comment by newtiny** [comment]
让大家来看看啊？

**Comment by rainyang** [comment]
我关闭是怕你影响我销售，你以为我怎样？你可以来芸众公司我们当面对峙



---原始邮件---
发件人: "一房两人三餐四季"<notifications@github.com&gt;
发送时间: 2020年12月4日(周五) 中午1:45
收件人: "sulianapp-com/sulianapp"<sulianapp@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"YangYu"<1315068148@qq.com&gt;;
主题: Re: [sulianapp-com/sulianapp] 可笑之极! (#5)




 
那我就呵呵了 为什么我联系芸众销售别人说没有你这样的代理呢？别关闭啊？

**Comment by rainyang** [comment]
去企查查查一下，我杨雨不光是代理，还是芸众股东



---原始邮件---
发件人: "一房两人三餐四季"<notifications@github.com&gt;
发送时间: 2020年12月4日(周五) 中午1:45
收件人: "sulianapp-com/sulianapp"<sulianapp@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"YangYu"<1315068148@qq.com&gt;;
主题: Re: [sulianapp-com/sulianapp] 可笑之极! (#5)




 
那我就呵呵了 为什么我联系芸众销售别人说没有你这样的代理呢？别关闭啊？

**Comment by rainyang** [comment]
跟我这搞什么事情



---原始邮件---
发件人: "一房两人三餐四季"<notifications@github.com&gt;
发送时间: 2020年12月4日(周五) 中午1:45
收件人: "sulianapp-com/sulianapp"<sulianapp@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"YangYu"<1315068148@qq.com&gt;;
主题: Re: [sulianapp-com/sulianapp] 可笑之极! (#5)




 
那我就呵呵了 为什么我联系芸众销售别人说没有你这样的代理呢？别关闭啊？

**Comment by rainyang** [comment]
呵呵，你联系哪个销售，搞笑，你去问韦平，我是不是代理



---原始邮件---
发件人: "一房两人三餐四季"<notifications@github.com&gt;
发送时间: 2020年12月4日(周五) 中午1:45
收件人: "sulianapp-com/sulianapp"<sulianapp@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"YangYu"<1315068148@qq.com&gt;;
主题: Re: [sulianapp-com/sulianapp] 可笑之极! (#5)




 
那我就呵呵了 为什么我联系芸众销售别人说没有你这样的代理呢？别关闭啊？

**Comment by rainyang** [comment]
你觉得我是盗版，去芸众或者公安局举报我啊，随时欢迎来查，否则就别秀了



---原始邮件---
发件人: "一房两人三餐四季"<notifications@github.com&gt;
发送时间: 2020年12月4日(周五) 中午1:45
收件人: "sulianapp-com/sulianapp"<sulianapp@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"YangYu"<1315068148@qq.com&gt;;
主题: Re: [sulianapp-com/sulianapp] 可笑之极! (#5)




 
让大家来看看啊？
